-- community_posts table
CREATE TABLE public.community_posts (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  image_url text not null,
  caption text,
  likes_count integer default 0,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint community_posts_pkey primary key (id),
  constraint community_posts_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
);

-- post_likes table
CREATE TABLE public.post_likes (
  id bigint generated by default as identity not null,
  post_id bigint not null,
  user_id uuid not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint post_likes_pkey primary key (id),
  constraint post_likes_post_id_fkey foreign key (post_id) references public.community_posts (id) on delete cascade,
  constraint post_likes_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade,
  constraint post_likes_post_id_user_id_key unique (post_id, user_id)
);

-- post_comments table
CREATE TABLE public.post_comments (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  post_id bigint not null,
  comment text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint post_comments_pkey primary key (id),
  constraint post_comments_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade,
  constraint post_comments_post_id_fkey foreign key (post_id) references public.community_posts (id) on delete cascade
);

-- Policies for community_posts
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read community posts" ON public.community_posts FOR SELECT USING (true);
CREATE POLICY "Users can insert their own community posts" ON public.community_posts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own community posts" ON public.community_posts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own community posts" ON public.community_posts FOR DELETE USING (auth.uid() = user_id);

-- Policies for post_likes
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read post likes" ON public.post_likes FOR SELECT USING (true);
CREATE POLICY "Users can insert their own post likes" ON public.post_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own post likes" ON public.post_likes FOR DELETE USING (auth.uid() = user_id);

-- Policies for post_comments
ALTER TABLE public.post_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read post comments" ON public.post_comments FOR SELECT USING (true);
CREATE POLICY "Users can insert their own post comments" ON public.post_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own post comments" ON public.post_comments FOR DELETE USING (auth.uid() = user_id);
