-- Likes table
CREATE TABLE public.likes (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  spot_id bigint not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint likes_pkey primary key (id),
  constraint likes_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade,
  constraint likes_spot_id_fkey foreign key (spot_id) references public.spots (id) on delete cascade,
  constraint likes_user_id_spot_id_key unique (user_id, spot_id)
);

-- Comments table
CREATE TABLE public.comments (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  spot_id bigint not null,
  comment text not null,
  rating integer not null constraint rating_check check (rating >= 1 and rating <= 5),
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint comments_pkey primary key (id),
  constraint comments_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade,
  constraint comments_spot_id_fkey foreign key (spot_id) references public.spots (id) on delete cascade
);

-- Policies for likes
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read likes" ON public.likes FOR SELECT USING (true);
CREATE POLICY "Users can insert their own likes" ON public.likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own likes" ON public.likes FOR DELETE USING (auth.uid() = user_id);

-- Policies for comments
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read comments" ON public.comments FOR SELECT USING (true);
CREATE POLICY "Users can insert their own comments" ON public.comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own comments" ON public.comments FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own comments" ON public.comments FOR UPDATE USING (auth.uid() = user_id);
